version: 43.0.9
pageUuid: a58fbb0e-ff26-11ed-adc6-4b2836e90b71
appTemplate:
  plugins:
    ordered:
      - text1:
          pluginTemplate:
            id: text1
            type: widget
            subtype: TextWidget2
            template:
              ordered:
                - heightType: auto
                - horizontalAlign: left
                - hidden: false
                - imageWidth: fit
                - showInEditor: false
                - verticalAlign: center
                - tooltipText: ''
                - value: <h3>{{ retoolContext.environment }}
                - _disclosedFields:
                    array: []
                - disableMarkdown: false
                - overflowType: scroll
                - maintainSpaceWhenHidden: false
            style:
              ordered: []
            position2:
              position2:
                row: 0.2
                col: 5
                height: 0.6
                width: 3
            createdAt: 2023-05-30T20:15:02.363Z
      - $main:
          pluginTemplate:
            id: $main
            type: frame
            subtype: Frame
            template:
              ordered:
                - type: main
                - sticky: false
                - isHiddenOnDesktop: false
                - isHiddenOnMobile: false
            style:
              ordered: []
            createdAt: 2023-05-30T20:15:02.388Z
      - query1:
          pluginTemplate:
            id: query1
            type: datasource
            subtype: JavascriptQuery
            resourceName: JavascriptQuery
            template:
              ordered:
                - queryRefreshTime: ''
                - lastReceivedFromResourceAt: null
                - queryDisabledMessage: ''
                - servedFromCache: false
                - offlineUserQueryInputs: ''
                - successMessage: ''
                - queryDisabled: ''
                - playgroundQuerySaveId: latest
                - workflowParams: null
                - resourceNameOverride: ''
                - runWhenModelUpdates: false
                - showFailureToaster: true
                - query: return retoolContext.environment
                - playgroundQueryUuid: ''
                - playgroundQueryId: null
                - error: null
                - workflowRunBodyType: raw
                - privateParams: []
                - runWhenPageLoadsDelay: ''
                - data: null
                - importedQueryInputs:
                    ordered: []
                - isImported: false
                - showSuccessToaster: true
                - cacheKeyTtl: ''
                - requestSentTimestamp: null
                - metadata: null
                - queryRunTime: null
                - changesetObject: ''
                - errorTransformer: >-
                    // The variable 'data' allows you to reference the request's
                    data in the transformer. 

                    // example: return data.find(element => element.isError)

                    return data.error
                - finished: null
                - confirmationMessage: null
                - isFetching: false
                - changeset: ''
                - rawData: null
                - queryTriggerDelay: '0'
                - resourceTypeOverride: null
                - watchedParams: []
                - enableErrorTransformer: false
                - showLatestVersionUpdatedWarning: false
                - timestamp: 0
                - importedQueryDefaults:
                    ordered: []
                - enableTransformer: false
                - showUpdateSetValueDynamicallyToggle: true
                - runWhenPageLoads: false
                - transformer: >-
                    // type your code here

                    // example: return formatDataAsArray(data).filter(row =>
                    row.quantity > 20)

                    return data
                - events: []
                - queryTimeout: '10000'
                - workflowId: null
                - requireConfirmation: false
                - queryFailureConditions: ''
                - changesetIsObject: false
                - enableCaching: false
                - allowedGroups: []
                - offlineQueryType: None
                - queryThrottleTime: '750'
                - updateSetValueDynamically: false
                - notificationDuration: ''
            createdAt: 2023-06-01T19:21:17.250Z
      - image1:
          pluginTemplate:
            id: image1
            type: widget
            subtype: ImageWidget2
            template:
              ordered:
                - heightType: auto
                - horizontalAlign: center
                - srcWidth: null
                - clickable: false
                - src: https://placekitten.com/400/300
                - hidden: false
                - srcHeight: null
                - showInEditor: false
                - tooltipText: ''
                - fit: cover
                - aspectRatio: null
                - storageBlobId: ''
                - altText: ''
                - dbBlobId: ''
                - events:
                    ordered: []
                - srcType: src
                - maintainSpaceWhenHidden: false
            style:
              ordered: []
            position2:
              position2:
                row: 2.4
                col: 5
                height: 3
                width: 2
            createdAt: 2023-06-06T22:57:51.537Z
  queryStatusVisibility: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: false
      runtimeV2OptOut: false
  rootScreen: null
  version: 2.121.1
  markdownLinkBehavior: auto
  experimentalDataTabEnabled: true
