version: 43.0.9
pageUuid: a58fbb0e-ff26-11ed-adc6-4b2836e90b71
appTemplate:
  plugins:
    ordered:
      - text1:
          pluginTemplate:
            id: text1
            type: widget
            subtype: TextWidget2
            template:
              ordered:
                - heightType: auto
                - horizontalAlign: left
                - hidden: false
                - imageWidth: fit
                - showInEditor: false
                - verticalAlign: center
                - tooltipText: ''
                - value: <h3>{{ retoolContext.environment }}
                - _disclosedFields:
                    array: []
                - disableMarkdown: false
                - overflowType: scroll
                - maintainSpaceWhenHidden: false
            style:
              ordered: []
            position2:
              position2:
                row: 0.2
                col: 5
                height: 0.6
                width: 3
            createdAt: 2023-05-30T20:15:02.363Z
      - $main:
          pluginTemplate:
            id: $main
            type: frame
            subtype: Frame
            template:
              ordered:
                - type: main
                - sticky: false
                - isHiddenOnDesktop: false
                - isHiddenOnMobile: false
            style:
              ordered: []
            createdAt: 2023-05-30T20:15:02.388Z
  queryStatusVisibility: false
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: false
      runtimeV2OptOut: false
  rootScreen: null
  version: 2.113.19
  markdownLinkBehavior: auto
  experimentalDataTabEnabled: true
